{{- $longhorn := .Values.longhorn }}
{{- range .Values.storageClasses }}
---
allowVolumeExpansion: {{ default true .allowVolumeExpansion }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ default false .default | quote }}
    argocd.argoproj.io/sync-wave: "1"
  name: {{ .name }}
parameters:
  dataEngine: {{ default $longhorn.persistence.dataEngine .dataEngine }}
  dataLocality: {{ default $longhorn.persistence.defaultDataLocality .dataLocality }}
  disableRevisionCounter: {{ default $longhorn.defaultSettings.disableRevisionCounter .disableRevisionCounter | quote }}
  {{- if .diskSelector }}
  diskSelector: {{ .diskSelector }}
  {{- end }}
  {{- if .freezeFSForSnapshot }}
  freezeFSForSnapshot: "true"
  {{- end }}
  fromBackup: {{ default "" .fromBackup }}
  fsType: {{ default "ext4" .fsType }}
  nfsOptions: {{ default "" .nfsOptions }}
  {{- if .nodeSelector }}
  nodeSelector: {{ .nodeSelector }}
  {{- end }}
  numberOfReplicas: {{ default 3 .numberOfReplicas | quote }}
  staleReplicaTimeout: {{ default 30 .staleReplicaTimeout | quote }}
  unmapMarkSnapChainRemoved: {{ default "ignored" .unmapMarkSnapChainRemoved }}
provisioner: {{ default "driver.longhorn.io" .provisioner }}
reclaimPolicy: {{ default "Retain" .reclaimPolicy }}
volumeBindingMode: {{ default "Immediate" .volumeBindingMode }}
{{- end }}
